AncientSettings: Updates Russian translations
Ancient-Lab/packages_apps_AncientSettings pull request #54
Opened 2020-06-05 17:34 UTC by CakesTwix

2020-06-05 17:42 UTC, AshutoshSundresh requested changes
Please remove the duplicate string

2020-06-05 17:42 UTC, AshutoshSundresh commented on res/values-ru/ancient_strings.xml
> +    <string name="volume_summary">Настройка параметров для кнопок громкости</string
Duplicate string

2020-06-05 18:16 UTC, CakesTwix commented on res/values-ru/ancient_strings.xml
> +    <string name="volume_summary">Настройка параметров для кнопок громкости</string
Excuse me. Corrected.

2020-06-06 07:43 UTC, merged

2020-06-06 11:41 UTC, AshutoshSundresh commented
Not well formed. Some strings were removed and closing brackets missing in some places.